In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')
from sklearn.neighbors import KDTree
import json
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle
from sklearn.neighbors import KDTree
os.chdir("/content/gdrive/My Drive/Colab Notebooks/yelp_dataset")
print(os.getcwd())
df = pd.read_csv("columncode.csv")
df

Mounted at /content/gdrive
/content/gdrive/.shortcut-targets-by-id/1m5dVPIYDUmApGRmzUSFDadtixbOm-Lu2/Colab Notebooks/yelp_dataset


Unnamed: 0.1  Unnamed: 0             business_id  \
0                 0           0  MTSW4McQd7CbVtyjqoe9mw   
1                 1           1  CF33F8-E6oudUQ46HnavjQ   
2                 2           2  bBDDEgkFA1Otx9Lfe7BZUQ   
3                 3           3  eEOYSgkmpB90uNA7lDOMRA   
4                 4           4  il_Ro8jwPlHresjw9EGmBg   
...             ...         ...                     ...   
34999         34999       34999  w_4xUt-1AyY2ZwKtnjW0Xg   
35000         35000       35000  l9eLGG9ZKpLJzboZq-9LRQ   
35001         35001       35001  cM6V90ExQD6KMSU3rRB5ZA   
35002         35002       35002  WnT9NIzQgLlILjPT0kEcsQ   
35003         35003       35003  2O2K6SXPWv56amqxCECd4w   

                                name              address             city  \
0                 St Honore Pastries          935 Race St     Philadelphia   
1                     Sonic Drive-In        615 S Main St     Ashland City   
2                     Sonic Drive-In  2312 Dickerson Pike        Nashville   
3              Vietnamese Food Truck                  NaN        Tampa Bay   
4                            Denny's         8901 US 31 S     Indianapolis   
...                              ...                  ...              ...   
34999           Bittercreek Alehouse         246 N 8th St            Boise   
35000                           Wawa      19 N Bishop Ave  Clifton Heights   
35001              Dutch Bros Coffee  1181 N Milwaukee St            Boise   
35002  Adelita Taqueria & Restaurant        1108 S 9th St     Philadelphia   
35003                   The Plum Pit      4405 Pennell Rd            Aston   

      state postal_code   latitude   longitude  ...  Coffee & Tea  Italian  \
0        PA       19107  39.955505  -75.155564  ...             1        0   
1        TN       37015  36.269593  -87.058943  ...             0        0   
2        TN       37207  36.208102  -86.768170  ...             0        0   
3        FL       33602  27.955269  -82.456320  ...             0        0   
4        IN       46227  39.637133  -86.127217  ...             0        0   
...     ...         ...        ...         ...  ...           ...      ...   
34999    ID       83702  43.616590 -116.202383  ...             0        0   
35000    PA       19018  39.925656  -75.310344  ...             1        0   
35001    ID       83704  43.615401 -116.284689  ...             1        0   
35002    PA       19147  39.935982  -75.158665  ...             0        0   
35003    DE       19014  39.856185  -75.427725  ...             0        0   

      Seafood Chicken Wings  Chinese  Event Planning & Services  Salad  Delis  \
0           0             0        0                          0      0      0   
1           0             0        0                          0      0      0   
2           0             0        0                          0      0      0   
3           0             0        0                          0      0      0   
4           0             0        0                          0      0      0   
...       ...           ...      ...                        ...    ...    ...   
34999       0             0        0                          0      0      0   
35000       0             0        0                          0      0      0   
35001       0             0        0                          0      0      0   
35002       0             0        0                          0      0      0   
35003       0             0        0                          1      0      0   

       Cafes  Caterers  
0          0         0  
1          0         0  
2          0         0  
3          0         0  
4          0         0  
...      ...       ...  
34999      0         0  
35000      0         0  
35001      1         0  
35002      0         0  
35003      0         1  

[35004 rows x 39 columns]

In [ ]:
df = df.drop(["Unnamed: 0.1","Unnamed: 0"], axis=1)
df

business_id                           name  \
0      MTSW4McQd7CbVtyjqoe9mw             St Honore Pastries   
1      CF33F8-E6oudUQ46HnavjQ                 Sonic Drive-In   
2      bBDDEgkFA1Otx9Lfe7BZUQ                 Sonic Drive-In   
3      eEOYSgkmpB90uNA7lDOMRA          Vietnamese Food Truck   
4      il_Ro8jwPlHresjw9EGmBg                        Denny's   
...                       ...                            ...   
34999  w_4xUt-1AyY2ZwKtnjW0Xg           Bittercreek Alehouse   
35000  l9eLGG9ZKpLJzboZq-9LRQ                           Wawa   
35001  cM6V90ExQD6KMSU3rRB5ZA              Dutch Bros Coffee   
35002  WnT9NIzQgLlILjPT0kEcsQ  Adelita Taqueria & Restaurant   
35003  2O2K6SXPWv56amqxCECd4w                   The Plum Pit   

                   address             city state postal_code   latitude  \
0              935 Race St     Philadelphia    PA       19107  39.955505   
1            615 S Main St     Ashland City    TN       37015  36.269593   
2      2312 Dickerson Pike        Nashville    TN       37207  36.208102   
3                      NaN        Tampa Bay    FL       33602  27.955269   
4             8901 US 31 S     Indianapolis    IN       46227  39.637133   
...                    ...              ...   ...         ...        ...   
34999         246 N 8th St            Boise    ID       83702  43.616590   
35000      19 N Bishop Ave  Clifton Heights    PA       19018  39.925656   
35001  1181 N Milwaukee St            Boise    ID       83704  43.615401   
35002        1108 S 9th St     Philadelphia    PA       19147  39.935982   
35003      4405 Pennell Rd            Aston    DE       19014  39.856185   

        longitude  stars  review_count  ... Coffee & Tea Italian  Seafood  \
0      -75.155564    0.8            80  ...            1       0        0   
1      -87.058943    0.4             6  ...            0       0        0   
2      -86.768170    0.3            10  ...            0       0        0   
3      -82.456320    0.8            10  ...            0       0        0   
4      -86.127217    0.5            28  ...            0       0        0   
...           ...    ...           ...  ...          ...     ...      ...   
34999 -116.202383    0.9           998  ...            0       0        0   
35000  -75.310344    0.6            11  ...            1       0        0   
35001 -116.284689    0.8            33  ...            1       0        0   
35002  -75.158665    0.9            35  ...            0       0        0   
35003  -75.427725    0.9            14  ...            0       0        0   

       Chicken Wings  Chinese  Event Planning & Services  Salad  Delis  Cafes  \
0                  0        0                          0      0      0      0   
1                  0        0                          0      0      0      0   
2                  0        0                          0      0      0      0   
3                  0        0                          0      0      0      0   
4                  0        0                          0      0      0      0   
...              ...      ...                        ...    ...    ...    ...   
34999              0        0                          0      0      0      0   
35000              0        0                          0      0      0      0   
35001              0        0                          0      0      0      1   
35002              0        0                          0      0      0      0   
35003              0        0                          1      0      0      0   

       Caterers  
0             0  
1             0  
2             0  
3             0  
4             0  
...         ...  
34999         0  
35000         0  
35001         0  
35002         0  
35003         1  

[35004 rows x 37 columns]

In [ ]:
def rando(x):
  if x ==0:
    x = np.random.uniform(0,0.1)
  return x
df = df.applymap(rando)

In [ ]:
#Only attributes included: Lat, long, stars, top 20 categories
X = df[['latitude_norm', 'longitude_norm', 'stars', 'price_range', 'Sandwiches', 'Nightlife',
       'Bars', 'American (Traditional)', 'Fast Food', 'Pizza',
       'Breakfast & Brunch', 'Burgers', 'American (New)', 'Mexican',
       'Coffee & Tea', 'Italian', 'Seafood', 'Chicken Wings', 'Chinese',
       'Event Planning & Services', 'Salad', 'Delis', 'Cafes', 'Caterers']]
X #Ensure everything is numeric

latitude_norm  longitude_norm  stars  price_range  Sandwiches  \
0           0.475702        0.923907    0.8     1.000000    0.005760   
1          -0.129146        0.059922    0.4     1.000000    1.000000   
2          -0.139236        0.081027    0.3     1.000000    0.065928   
3          -1.493504        0.393995    0.8     1.566924    0.061229   
4           0.423458        0.127549    0.5     1.000000    0.074628   
...              ...             ...    ...          ...         ...   
34999       1.076476       -2.055403    0.9     2.000000    1.000000   
35000       0.470804        0.912673    0.6     1.000000    1.000000   
35001       1.076281       -2.061377    0.8     1.000000    0.000423   
35002       0.472499        0.923682    0.9     2.000000    0.039139   
35003       0.459404        0.904153    0.9     1.000000    0.028045   

       Nightlife      Bars  American (Traditional)  Fast Food     Pizza  ...  \
0       0.029525  0.029550                0.094624   0.097367  0.091759  ...   
1       0.013361  0.033487                0.095488   1.000000  0.096595  ...   
2       0.031828  0.044529                0.090377   1.000000  0.084064  ...   
3       0.093231  0.019350                0.097288   0.028745  0.088396  ...   
4       0.069725  0.037405                1.000000   0.005237  0.098686  ...   
...          ...       ...                     ...        ...       ...  ...   
34999   1.000000  1.000000                0.064811   0.031628  0.041228  ...   
35000   0.077125  0.052748                0.095989   0.096394  0.024062  ...   
35001   0.036964  1.000000                0.025993   0.005711  0.031306  ...   
35002   0.084215  0.090091                0.092995   0.098999  0.090061  ...   
35003   0.074783  0.014606                0.085598   0.083993  0.075256  ...   

       Coffee & Tea   Italian   Seafood  Chicken Wings   Chinese  \
0          1.000000  0.016360  0.006282       0.020231  0.014308   
1          0.007342  0.067822  0.002445       0.069897  0.001039   
2          0.014183  0.051555  0.003778       0.019103  0.080766   
3          0.067124  0.048648  0.065320       0.051963  0.072436   
4          0.050024  0.002914  0.060165       0.036115  0.052689   
...             ...       ...       ...            ...       ...   
34999      0.082077  0.022481  0.025888       0.090125  0.013281   
35000      1.000000  0.011012  0.098764       0.033518  0.016895   
35001      1.000000  0.078980  0.026251       0.030739  0.033370   
35002      0.090850  0.093363  0.021978       0.058746  0.007487   
35003      0.088951  0.009025  0.008266       0.058443  0.001261   

       Event Planning & Services     Salad     Delis     Cafes  Caterers  
0                       0.066864  0.049023  0.040685  0.030258  0.054292  
1                       0.045736  0.073214  0.036819  0.068958  0.008393  
2                       0.012579  0.004100  0.005735  0.038555  0.091518  
3                       0.031421  0.097303  0.012796  0.001930  0.082350  
4                       0.089112  0.038373  0.099908  0.087467  0.075876  
...                          ...       ...       ...       ...       ...  
34999                   0.054860  0.061408  0.039850  0.068787  0.078542  
35000                   0.093695  0.055529  0.077773  0.086630  0.079488  
35001                   0.063734  0.058741  0.096203  1.000000  0.079565  
35002                   0.017831  0.021316  0.075345  0.044760  0.034687  
35003                   1.000000  0.044600  0.020634  0.002583  1.000000  

[35004 rows x 24 columns]

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

df['distances'] = cosine_similarity(X, X.iloc[0:1]) # Here I assume that the parent vector is stored as the first row in the dataframe, but you could also store it separately
df
'''n = 10 # or however many you want
n_largest = df['distances'].nlargest(n + 1) # this contains the parent itself as the most similar entry, hence n+1 to get n children
n_largest'''

"n = 10 # or however many you want\nn_largest = df['distances'].nlargest(n + 1) # this contains the parent itself as the most similar entry, hence n+1 to get n children\nn_largest"

In [ ]:
df

Unnamed: 0.1  Unnamed: 0             business_id  \
0                 0           0  MTSW4McQd7CbVtyjqoe9mw   
1                 1           1  CF33F8-E6oudUQ46HnavjQ   
2                 2           2  bBDDEgkFA1Otx9Lfe7BZUQ   
3                 3           3  eEOYSgkmpB90uNA7lDOMRA   
4                 4           4  il_Ro8jwPlHresjw9EGmBg   
...             ...         ...                     ...   
34999         34999       34999  w_4xUt-1AyY2ZwKtnjW0Xg   
35000         35000       35000  l9eLGG9ZKpLJzboZq-9LRQ   
35001         35001       35001  cM6V90ExQD6KMSU3rRB5ZA   
35002         35002       35002  WnT9NIzQgLlILjPT0kEcsQ   
35003         35003       35003  2O2K6SXPWv56amqxCECd4w   

                                name              address             city  \
0                 St Honore Pastries          935 Race St     Philadelphia   
1                     Sonic Drive-In        615 S Main St     Ashland City   
2                     Sonic Drive-In  2312 Dickerson Pike        Nashville   
3              Vietnamese Food Truck                  NaN        Tampa Bay   
4                            Denny's         8901 US 31 S     Indianapolis   
...                              ...                  ...              ...   
34999           Bittercreek Alehouse         246 N 8th St            Boise   
35000                           Wawa      19 N Bishop Ave  Clifton Heights   
35001              Dutch Bros Coffee  1181 N Milwaukee St            Boise   
35002  Adelita Taqueria & Restaurant        1108 S 9th St     Philadelphia   
35003                   The Plum Pit      4405 Pennell Rd            Aston   

      state postal_code   latitude   longitude  ...  Italian  Seafood  \
0        PA       19107  39.955505  -75.155564  ...        0        0   
1        TN       37015  36.269593  -87.058943  ...        0        0   
2        TN       37207  36.208102  -86.768170  ...        0        0   
3        FL       33602  27.955269  -82.456320  ...        0        0   
4        IN       46227  39.637133  -86.127217  ...        0        0   
...     ...         ...        ...         ...  ...      ...      ...   
34999    ID       83702  43.616590 -116.202383  ...        0        0   
35000    PA       19018  39.925656  -75.310344  ...        0        0   
35001    ID       83704  43.615401 -116.284689  ...        0        0   
35002    PA       19147  39.935982  -75.158665  ...        0        0   
35003    DE       19014  39.856185  -75.427725  ...        0        0   

      Chicken Wings Chinese  Event Planning & Services  Salad  Delis  Cafes  \
0                 0       0                          0      0      0      0   
1                 0       0                          0      0      0      0   
2                 0       0                          0      0      0      0   
3                 0       0                          0      0      0      0   
4                 0       0                          0      0      0      0   
...             ...     ...                        ...    ...    ...    ...   
34999             0       0                          0      0      0      0   
35000             0       0                          0      0      0      0   
35001             0       0                          0      0      0      1   
35002             0       0                          0      0      0      0   
35003             0       0                          1      0      0      0   

       Caterers  distances  
0             0   1.000000  
1             0   0.106738  
2             0   0.103638  
3             0   0.102327  
4             0   0.278890  
...         ...        ...  
34999         0  -0.133370  
35000         0   0.835820  
35001         0   0.049885  
35002         0   0.641759  
35003         1   0.548994  

[35004 rows x 40 columns]

In [ ]:
#Build Tree
tree = KDTree(X)   #for some reason cosine doesn't work. It's wack and makes me sad

s = pickle.dumps(tree)
tree_copy = pickle.loads(s)
dist, ind = tree_copy.query(X, k=11)

print(ind)  # indices of closest neighbors
print(dist)  # distances to closest neighbors

[[    0 26442 21261 ... 29547  2108 21282]
 [    1 15408 20357 ... 15484  3055 34975]
 [    2 15773 21026 ... 33414 15625   914]
 ...
 [35001 15947  8959 ... 19959 15544   531]
 [35002  6263 32596 ... 26592 32659 15329]
 [35003 31089 33407 ... 28328 10782 11355]]
[[0.         0.11534421 0.16626683 ... 0.17827259 0.17844601 0.1791569 ]
 [0.         0.2079946  0.22438298 ... 0.4987358  0.51464532 0.51563772]
 [0.         0.13730244 0.14364965 ... 0.16149786 0.16309877 0.16358471]
 ...
 [0.         0.16078412 0.17042758 ... 0.97286817 0.98560193 0.9987849 ]
 [0.         0.14494399 0.15305376 ... 0.16345038 0.16592489 0.16649827]
 [0.         0.15838728 0.16823428 ... 0.18839917 0.18887771 0.19666386]]


In [ ]:
tops= pd.DataFrame(ind, columns = ["match","similar1","similar2","similar3", "similar4",'similar5', 'similar6', 'similar7', 'similar8', 'similar9', 'similar10'])
#It's at this point where we would want to map to the business ID
tops = tops.drop(['match'], axis=1)

def addcol(string):
  df[string] = tops[string]
for i in tops.columns:
  addcol(i)
df

Unnamed: 0.1  Unnamed: 0             business_id  \
0                 0           0  MTSW4McQd7CbVtyjqoe9mw   
1                 1           1  CF33F8-E6oudUQ46HnavjQ   
2                 2           2  bBDDEgkFA1Otx9Lfe7BZUQ   
3                 3           3  eEOYSgkmpB90uNA7lDOMRA   
4                 4           4  il_Ro8jwPlHresjw9EGmBg   
...             ...         ...                     ...   
34999         34999       34999  w_4xUt-1AyY2ZwKtnjW0Xg   
35000         35000       35000  l9eLGG9ZKpLJzboZq-9LRQ   
35001         35001       35001  cM6V90ExQD6KMSU3rRB5ZA   
35002         35002       35002  WnT9NIzQgLlILjPT0kEcsQ   
35003         35003       35003  2O2K6SXPWv56amqxCECd4w   

                                name              address             city  \
0                 St Honore Pastries          935 Race St     Philadelphia   
1                     Sonic Drive-In        615 S Main St     Ashland City   
2                     Sonic Drive-In  2312 Dickerson Pike        Nashville   
3              Vietnamese Food Truck                  NaN        Tampa Bay   
4                            Denny's         8901 US 31 S     Indianapolis   
...                              ...                  ...              ...   
34999           Bittercreek Alehouse         246 N 8th St            Boise   
35000                           Wawa      19 N Bishop Ave  Clifton Heights   
35001              Dutch Bros Coffee  1181 N Milwaukee St            Boise   
35002  Adelita Taqueria & Restaurant        1108 S 9th St     Philadelphia   
35003                   The Plum Pit      4405 Pennell Rd            Aston   

      state postal_code   latitude   longitude  ...  similar1  similar2  \
0        PA       19107  39.955505  -75.155564  ...     31094      2108   
1        TN       37015  36.269593  -87.058943  ...      5055     15408   
2        TN       37207  36.208102  -86.768170  ...     33414     17958   
3        FL       33602  27.955269  -82.456320  ...       211     17030   
4        IN       46227  39.637133  -86.127217  ...      7822      1696   
...     ...         ...        ...         ...  ...       ...       ...   
34999    ID       83702  43.616590 -116.202383  ...     32996      4757   
35000    PA       19018  39.925656  -75.310344  ...      7889     10751   
35001    ID       83704  43.615401 -116.284689  ...     15947      8959   
35002    PA       19147  39.935982  -75.158665  ...     26592      9978   
35003    DE       19014  39.856185  -75.427725  ...      3322     15531   

      similar3 similar4  similar5  similar6  similar7  similar8  similar9  \
0        26442    28649     27502      7592     12797       623      9829   
1        20357    32954      1186     15484     19674     31579     34975   
2        23935    31819     30075     20874     13849     21921     20967   
3         6525    23992     16260     10959     16859      7311     14613   
4        23280    18228      9791     28456      9331     13636     10425   
...        ...      ...       ...       ...       ...       ...       ...   
34999    29564    14987     30369     15588     19787     27343     27299   
35000    22043     5435     28191     31084      5721       314      5668   
35001    25551    18075     19029     24147     15544       531     34063   
35002    31306    32596      9166     14347       452     15329     31302   
35003    12586    27734      3697     33407     31089     15369     21230   

       similar10  
0          10945  
1          10138  
2           6759  
3           9950  
4           3122  
...          ...  
34999      13695  
35000      33853  
35001      19959  
35002      25352  
35003       7279  

[35004 rows x 49 columns]

In [ ]:
#Turn index into business ID
for i in range(1, 11):
    similar_col = 'similar' + str(i)
    row_nums = df[similar_col]
    business_ids = df.loc[row_nums, 'business_id'].reset_index(drop=True)
    new_col_name = similar_col + '_id'
    df[new_col_name] = business_ids

df

Unnamed: 0             business_id                           name  \
0               0  MTSW4McQd7CbVtyjqoe9mw             St Honore Pastries   
1               1  CF33F8-E6oudUQ46HnavjQ                 Sonic Drive-In   
2               2  bBDDEgkFA1Otx9Lfe7BZUQ                 Sonic Drive-In   
3               3  eEOYSgkmpB90uNA7lDOMRA          Vietnamese Food Truck   
4               4  il_Ro8jwPlHresjw9EGmBg                        Denny's   
...           ...                     ...                            ...   
34999       34999  w_4xUt-1AyY2ZwKtnjW0Xg           Bittercreek Alehouse   
35000       35000  l9eLGG9ZKpLJzboZq-9LRQ                           Wawa   
35001       35001  cM6V90ExQD6KMSU3rRB5ZA              Dutch Bros Coffee   
35002       35002  WnT9NIzQgLlILjPT0kEcsQ  Adelita Taqueria & Restaurant   
35003       35003  2O2K6SXPWv56amqxCECd4w                   The Plum Pit   

                   address             city state postal_code   latitude  \
0              935 Race St     Philadelphia    PA       19107  39.955505   
1            615 S Main St     Ashland City    TN       37015  36.269593   
2      2312 Dickerson Pike        Nashville    TN       37207  36.208102   
3                      NaN        Tampa Bay    FL       33602  27.955269   
4             8901 US 31 S     Indianapolis    IN       46227  39.637133   
...                    ...              ...   ...         ...        ...   
34999         246 N 8th St            Boise    ID       83702  43.616590   
35000      19 N Bishop Ave  Clifton Heights    PA       19018  39.925656   
35001  1181 N Milwaukee St            Boise    ID       83704  43.615401   
35002        1108 S 9th St     Philadelphia    PA       19147  39.935982   
35003      4405 Pennell Rd            Aston    DE       19014  39.856185   

        longitude  stars  ...             similar1_id             similar2_id  \
0      -75.155564    4.0  ...  i6jA8vSHrP9LiUPHlqPVwA  htO_nlxkEsYHzDrtbiUxew   
1      -87.058943    2.0  ...  gzTZ_T24anSSHRHaZ8q_cg  GkiF5eV332J34-mgElgvKw   
2      -86.768170    1.5  ...  wuqsyYfgpg1xSh2Xf3Ld5A  lqrY1tHhPkZsiOPfpoydvw   
3      -82.456320    4.0  ...  rBE5TT_ndOOczNBrbRnJwA  x1ukXOcMHlzKmTmfNIjyLA   
4      -86.127217    2.5  ...  sgVG6oEvEOrG_SRc4R2-kA  nTuw1aT5_TvDEmfPkjdLMg   
...           ...    ...  ...                     ...                     ...   
34999 -116.202383    4.5  ...  1LLXrKlTbnKGVLvJQ72Xpw  kvOorg6F1gnbPmlTtjunsg   
35000  -75.310344    3.0  ...  sGdpqF3LRPMJfr7ickXlgg  foh6hwQxjCs0SeLT5MO1SQ   
35001 -116.284689    4.0  ...  OAbrYeHibZHdv3ch8nOrbw  xQ6CMjWbhm_sDWKvthgCWQ   
35002  -75.158665    4.5  ...  5S8GAXKwiu4K7gtd2z0Osw  V4Dr3ragKHKeUab96miyMA   
35003  -75.427725    4.5  ...  nCZR84HJcR1MTjDrJfHkcg  3omPdJWZzRAaNZU4vaovZQ   

                  similar3_id             similar4_id             similar5_id  \
0      WmGSfx0JbwNRT03ozyjb6A  gwxNttwUgmOn3vsHYe0pDQ  41LEg4ZgFDVnZfToxGXiGA   
1      78yGUXkvlchM94xegg6rpg  Kss1AJwPKXt6iqbxJJTGvA  W5jc_izjrwmr7fJzCJ2Cwg   
2      nF8Sb_G2PtT9ZHtgGYl69Q  Ybb1739zfXNm3ZZwa8c6Xg  OE_ryT0GUN1LO6y6yPuFZA   
3      JtR478zXy-jJn0tbGUn7yQ  oMTXtSJzEiHudUY3T68sPg  OnlFBPc0aCmzXjbYXKfnTA   
4      -v23pO9PUja15AiuUOW6tg  dB2e0wNXmLbnsVc_tyhkAg  fma5PhETY9wxzn1nO4d0Gg   
...                       ...                     ...                     ...   
34999  PWGcA2s9sf4iMb4dcLz6Hg  qCojkwO9wJX7alM-x-DJcA  clbAIdxK0CnqABhIwd6TCA   
35000  MCNO7rSHfFj4tllpFkMwSA  DTwt8_pCuGyQbiIfXNdhDw  RXwaoArqhi_-JnZh5MH_ow   
35001  b36EeutJRvowZMr9TpQm0w  8u70WVawnsReBWNv7IXNSg  P9ltq8KT6pgKjyZSKspHfA   
35002  KZyyoQ_nxLMyzO4d_Ts-NQ  6CpCnFzpyOV4ymhNP1AOGw  G1PbNo1yYxAu7G6b6sXZiw   
35003  ofjC1sFI2_r-pAvejek0JA  j58chGXdwNBjXYGCOHpxag  o7pgTVJqX2PYWbotk1uMug   

                  similar6_id             similar7_id             similar8_id  \
0      mv9uuDPJDaxl0zJ5cEhpXA  IjMs1n7UelI7ev_5IDl5kA  14ZGwnDyydXdSBsLXpSUrA   
1      iq-ST5E57wVE2pMj_Y3UBw  TghikeYc56lcmet_KwkYCA  VO_MNlz8rXOAsToaaa

In [ ]:
df.to_csv("pntest.csv")